name: 'Hello World'
description: 'Greet someone'
branding:
  icon: "check-circle"
  color: "green"
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: '${{github.actor}}'
outputs:
  random-number:
    description: "Random number"
    value: ${{steps.random-number-generator.outputs.random-id}}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    
    - id: random-number-generator
      run: echo "{random-id}={$RANDOM}" >> $GITHUB_OUTPUT
      shell: bash

    - run: echo "random number ${{steps.random-number-generator.outputs.random-id}}"
      shell: bash

    - run: echo "Goodbye $YOU"
      shell: bash
      env:
        YOU: ${{ inputs.who-to-greet }}